kind: llm
spec:
  name: llm-1
  type: openai
  config:
    model_name: openai

---
kind: agent
spec:
  name: ReAct-agent
  type: react
  config:
    llm: llm-1
    instruction: You are an agent for Browser automation.
    max_iterations: 20
    summarize_tool_response: false

---
kind: benchmark
spec:
  description: Benchmark for mcpmark Playwright WebArena tasks.
  agent: ReAct-agent
  tasks:
    # Reddit tasks （7）
    - mcpmark/configs/playwright_webarena/reddit/ai_data_analyst.json
    - mcpmark/configs/playwright_webarena/reddit/budget_europe_travel.json
    - mcpmark/configs/playwright_webarena/reddit/buyitforlife_research.json
    - mcpmark/configs/playwright_webarena/reddit/llm_research_summary.json
    - mcpmark/configs/playwright_webarena/reddit/movie_reviewer_analysis.json
    - mcpmark/configs/playwright_webarena/reddit/nba_statistics_analysis.json
    - mcpmark/configs/playwright_webarena/reddit/routine_tracker_forum.json
    
    # Shopping tasks （7）
    - mcpmark/configs/playwright_webarena/shopping/gaming_accessories_analysis.json
    - mcpmark/configs/playwright_webarena/shopping/advanced_product_analysis.json
    - mcpmark/configs/playwright_webarena/shopping/holiday_baking_competition.json
    - mcpmark/configs/playwright_webarena/shopping/health_routine_optimization.json
    - mcpmark/configs/playwright_webarena/shopping/multi_category_budget_analysis.json
    - mcpmark/configs/playwright_webarena/shopping/printer_keyboard_search.json
    - mcpmark/configs/playwright_webarena/shopping/running_shoes_purchase.json
    
    # Shopping Admin tasks （7）
    - mcpmark/configs/playwright_webarena/shopping_admin/marketing_customer_analysis.json
    - mcpmark/configs/playwright_webarena/shopping_admin/customer_segmentation_setup.json
    - mcpmark/configs/playwright_webarena/shopping_admin/fitness_promotion_strategy.json
    - mcpmark/configs/playwright_webarena/shopping_admin/ny_expansion_analysis.json
    - mcpmark/configs/playwright_webarena/shopping_admin/products_sales_analysis.json
    - mcpmark/configs/playwright_webarena/shopping_admin/sales_inventory_analysis.json
    - mcpmark/configs/playwright_webarena/shopping_admin/search_filtering_operations.json
