kind: llm
spec:
  name: llm-1
  type: openai
  config:
    model_name: gpt-4.1

---
kind: agent
spec:
  name: FunctionCall-agent
  type: function_call
  config:
    llm: llm-1
    instruction: You are an agent for financial analysis. If you need to calculate the result, you can use the calculator tool.
    max_iterations: 20
    summarize_tool_response: false
    servers:
      - name: yfinance
      - name: calculator

---
kind: benchmark
spec:
  description: Test agent for yfinance tasks.
  agent: FunctionCall-agent
  tasks:
    - mcpuniverse/financial_analysis/yfinance_task_0001.json
    - mcpuniverse/financial_analysis/yfinance_task_0002.json
    - mcpuniverse/financial_analysis/yfinance_task_0003.json
    - mcpuniverse/financial_analysis/yfinance_task_0004.json
    - mcpuniverse/financial_analysis/yfinance_task_0005.json
    - mcpuniverse/financial_analysis/yfinance_task_0006.json
    - mcpuniverse/financial_analysis/yfinance_task_0007.json
    - mcpuniverse/financial_analysis/yfinance_task_0008.json
    - mcpuniverse/financial_analysis/yfinance_task_0009.json
    - mcpuniverse/financial_analysis/yfinance_task_0010.json
    - mcpuniverse/financial_analysis/yfinance_task_0011.json
    - mcpuniverse/financial_analysis/yfinance_task_0012.json
    - mcpuniverse/financial_analysis/yfinance_task_0013.json
    - mcpuniverse/financial_analysis/yfinance_task_0014.json
    - mcpuniverse/financial_analysis/yfinance_task_0015.json
    - mcpuniverse/financial_analysis/yfinance_task_0016.json
    - mcpuniverse/financial_analysis/yfinance_task_0017.json
    - mcpuniverse/financial_analysis/yfinance_task_0018.json
    - mcpuniverse/financial_analysis/yfinance_task_0019.json
    - mcpuniverse/financial_analysis/yfinance_task_0020.json
    - mcpuniverse/financial_analysis/yfinance_task_0021.json
    - mcpuniverse/financial_analysis/yfinance_task_0022.json
    - mcpuniverse/financial_analysis/yfinance_task_0023.json
    - mcpuniverse/financial_analysis/yfinance_task_0024.json
    - mcpuniverse/financial_analysis/yfinance_task_0025.json
    - mcpuniverse/financial_analysis/yfinance_task_0026.json
    - mcpuniverse/financial_analysis/yfinance_task_0027.json
    - mcpuniverse/financial_analysis/yfinance_task_0028.json
    - mcpuniverse/financial_analysis/yfinance_task_0029.json
    - mcpuniverse/financial_analysis/yfinance_task_0030.json
    - mcpuniverse/financial_analysis/yfinance_task_0031.json
    - mcpuniverse/financial_analysis/yfinance_task_0032.json
    - mcpuniverse/financial_analysis/yfinance_task_0033.json
    - mcpuniverse/financial_analysis/yfinance_task_0034.json
    - mcpuniverse/financial_analysis/yfinance_task_0035.json
    - mcpuniverse/financial_analysis/yfinance_task_0036.json
    - mcpuniverse/financial_analysis/yfinance_task_0037.json
    - mcpuniverse/financial_analysis/yfinance_task_0038.json
    - mcpuniverse/financial_analysis/yfinance_task_0039.json
    - mcpuniverse/financial_analysis/yfinance_task_0040.json