kind: llm
spec:
  name: llm-1
  type: LiteLLMModel
  config:
    # model_name: GCP/claude-4-sonnet
    model_name: Azure/gpt-5-chat-2025-08-07

---
kind: agent
spec:
  name: FunctionCall-agent
  type: function_call
  config:
    llm: llm-1
    instruction: You are an agent for financial analysis. If you need to calculate the result, you can use the calculator tool.
    max_iterations: 20
    summarize_tool_response: false
    servers:
      - name: yfinance
      - name: calculator

---
kind: benchmark
spec:
  description: Test agent for yfinance tasks.
  agent: FunctionCall-agent
  tasks:
    - mcpuniverse/tsfm/tsfm_task_001.json
  